[build]
  publish = "."

# Send ALL Identity flows back to /admin/
[[redirects]]
  from = "/.netlify/identity/confirm"
  to = "/admin/"
  status = 301
  force = true

[[redirects]]
  from = "/.netlify/identity/verify"
  to = "/admin/"
  status = 301
  force = true

[[redirects]]
  from = "/.netlify/identity/recover"
  to = "/admin/"
  status = 301
  force = true

[[redirects]]
  from = "/.netlify/identity/authorize"
  to = "/admin/"
  status = 301
  force = true
