backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "site"
    label: "Site Content"
    files:
      - file: "content/site.json"
        label: "Main Content"
        name: "site"
        fields:
          - { label: "Business Name", name: "name", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "Service Area", name: "area", widget: "string" }
          - { label: "Hours", name: "hours", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Address", name: "address", widget: "string", required: false }
          - { label: "About Paragraph", name: "about", widget: "text" }
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Items", name: "items", widget: "list", field: { label: "Item", name: "item", widget: "string" } }
