backend:
  name: git-gateway
  branch: main

media_folder: "content/assets"
public_folder: "/content/assets"

collections:
  - name: "site"
    label: "Site Content"
    files:
      - file: "content/site.json"
        label: "Main Content"
        name: "main"
        fields:
          - { label: "Business Name", name: "name", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "Service Area", name: "area", widget: "string" }
          - { label: "Hours", name: "hours", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Address", name: "address", widget: "string", required: false }
          - { label: "About Text", name: "about", widget: "text" }
